default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") %>
  port: <%= ENV.fetch("DB_PORT") %>
  username: <%= ENV.fetch("DB_USERNAME") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>
  database: <%= ENV.fetch("DB_NAME") %>
  sslmode: <%= ENV.fetch("DB_SSLMODE", "require") %>

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV.fetch("DB_TEST_NAME") { "neondb_test" } %>

production:
  <<: *default